---
title: "Application 4: Boston Housing Data"
format: html
execute:
  message: false
  warning: false
  cache: true
---

```{r}
#| label: setup
source("_common.R")
```

## Data Loading

```{r}
library(MASS)
data("Boston")
X <- as.matrix(Boston[,-c(4,9,14)]) 
y = Boston$medv

# Combine into one data frame
df <- data.frame(X)
df$y <- y

# Export
write.csv(df, "boston_gp_input.csv", row.names = FALSE)


fit_data <- list(
  N = nrow(X),
  y = y,
  P = ncol(X), 
  X = apply(X, 2, rescale_to_range1),
  M = 40
)
```

## Exploratory Visualizations
```{r}
df <- as.data.frame(cbind(y, X))
df |> 
  gather(key, val, -y) %>%
  ggplot(aes(x = val, y = y)) +
  geom_point() +
  stat_smooth(method = "gam", se = TRUE, col = "blue") +
  facet_wrap(~key, scales = "free") +
  theme_gray() +
  ggtitle("Marginal scatter plot") 
```

## GAM

```{r}
library(mgcv)

gam_data <- data.frame(
  y = y,
  X
)

gam_fit <- gam(y ~ crim + zn + indus + nox + rm + age + dis + tax +
                ptratio + black + lstat +
                s(crim) + s(zn) + s(indus) + s(nox) + s(rm) + s(age) + 
                s(dis) + s(tax) + s(ptratio) + s(black) + s(lstat),
                data = gam_data,
                method = "REML")

summary(gam_fit)
```


```{r}
par(mfrow = c(3, 4), mar = c(4, 4, 2, 1), oma = c(1, 1, 2, 1))

predictor_names <- colnames(X)

for (pred in predictor_names) {
  # Plot original scatter points
  plot(gam_data[[pred]], gam_data$y, 
       pch = 16, cex = 0.5, col = "blue4",
       main = pred,
       xlab = pred, 
       ylab = "y")
  
  # Generate sequence for prediction
  x_seq <- seq(min(gam_data[[pred]]), max(gam_data[[pred]]), length.out = 100)
  
  # Create newdata for prediction: set current predictor to x_seq, others to their means
  newdata <- data.frame(matrix(rep(colMeans(gam_data[, -1]), each = 100), nrow = 100, byrow = FALSE))
  colnames(newdata) <- colnames(gam_data)[-1]
  newdata[[pred]] <- x_seq
  
  # Predict fitted values and SE
  pred_vals <- predict(gam_fit, newdata = newdata, se.fit = TRUE)
  
  # Add fitted line and confidence bands
  lines(x_seq, pred_vals$fit, col = "red", lwd = 2)
  lines(x_seq, pred_vals$fit + 1.96 * pred_vals$se.fit, col = "red", lty = 2)
  lines(x_seq, pred_vals$fit - 1.96 * pred_vals$se.fit, col = "red", lty = 2)
}

# Add overall title and reset plot layout
mtext("GAM Fitted Trends", outer = TRUE, cex = 1.2)
par(mfrow = c(1, 1))
```


## HSGP Model Fitting
```{r}
fit_a4_indep_hsgp <- fit_model(
        gp_hsgp_02,
        data = fit_data,
        chains = 2,
        iter = 5500,
        warmup = 500
      )

fit_a4_dep_hsgp <- fit_model(
        gp_hsgp_01,
        data = fit_data,
        chains = 2,
        iter = 5500,
        warmup = 500
      )
```

```{r}
print_quick_summary(fit_a4_indep_hsgp)
print_quick_summary(fit_a4_dep_hsgp)
```

```{r}
compute_savage_dickey_ratios(fit_a4_indep_hsgp)
compute_savage_dickey_ratios(fit_a4_dep_hsgp)
```

```{r}
plot_partial_hsgp(fit_a4_indep_hsgp)
plot_partial_hsgp(fit_a4_dep_hsgp)
```

## model fit with full GP
```{r}
fit_a4_dep <- fit_model(
        gp_add_p1_15,
        X = X,
        y = y,
        chains = 2,
        iter = 5500,
        warmup = 500
)
summary_gp_fit(fit_a4_dep)
```

saveRDS(fit_a4_dep, file = "analysis/application/fits/fit_a4_dep.rds")
fit_a4_dep <- readRDS("analysis/application/fits/fit_a4_dep.rds")

### non-local priors on delta

```{r}
fit_a4_dep_p2 <- fit_model(
        gp_add_p2_15,
        data = fit_data,
        chains = 2,
        iter = 5500,
        warmup = 500
)
# saveRDS(fit_a4_dep_p2, file = "analysis/application/fits/fit_a4_dep_p2.rds")
# fit_a4_dep_p2 <- readRDS("analysis/application/fits/fit_a4_dep_p2.rds")
```

## Results & Diagnostics
```{r}
print_quick_summary(fit_a4_dep)
print_quick_summary(fit_a4_dep_p2, key_params = c("delta2", "lambda", "sigma", "beta1"))
```


```{r}
plot_gp_trends(fit_a4_dep, model_name="exact-GP / multivariate-θ",ylim=c(0,50))
```


```{r}
compute_savage_dickey_ratios(fit_a4_dep)
compute_savage_dickey_ratios(fit_a4_dep_p2)
```

```{r}
plot_posterior_delta(fit_a4_dep, plot_prior=TRUE, bins=50, ylim=c(0,0.8))
plot_posterior_theta(fit_a4_dep, plot_prior=TRUE, bins=50, ylim=c(0,1.5))
```



```{r}
apply(fit_a4_dep$coef_orig$beta1_draws[,c(5,9,11)], 2, mean)
```